2018-12-16 20:28:24.139 [error] <0.457.0> Failed to start Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' in ranch_tcp:listen([{port,4000}]) for reason eaddrinuse (address already in use)
2018-12-16 20:28:24.164 [error] <0.455.0> Supervisor {<0.455.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.WebsheetsWeb.Endpoint.HTTP', 100, ranch_tcp, [{max_connections,16384},{port,4000}]) at undefined exit with reason {listen_error,'Elixir.WebsheetsWeb.Endpoint.HTTP',eaddrinuse} in context start_error
2018-12-19 21:22:51.982 [error] <0.570.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 gen_server <0.570.0> terminated with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<"2">>,<<"input_id">> => <<"i1,0">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 21:22:52.020 [error] <0.570.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<"2">>,<<"input_id">> => <<"i1,0">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 21:24:28.581 [error] <0.570.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 gen_server <0.570.0> terminated with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<>>,<<"input_id">> => <<"i0,1">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 21:24:28.599 [error] <0.570.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 CRASH REPORT Process <0.570.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<>>,<<"input_id">> => <<"i0,1">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 21:24:31.198 [error] <0.573.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 gen_server <0.573.0> terminated with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<"2">>,<<"input_id">> => <<"i0,1">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 21:24:31.202 [error] <0.573.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:15 CRASH REPORT Process <0.573.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.WebsheetsWeb.UpdateChannel':handle_in(<<"client_update">>, #{<<"body">> => <<"2">>,<<"input_id">> => <<"i0,1">>}, #{'__struct__' => 'Elixir.Phoenix.Socket',assigns => #{},channel => 'Elixir.WebsheetsWeb.UpdateChannel',...}) line 15
2018-12-19 23:42:12.660 [error] <0.601.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.36>,ranch_tcp,keepalive,<0.601.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55124},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-19 23:43:15.235 [error] <0.613.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.39>,ranch_tcp,keepalive,<0.613.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55130},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-19 23:43:21.838 [error] <0.627.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.42>,ranch_tcp,keepalive,<0.627.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55136},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-19 23:44:50.525 [error] <0.643.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.45>,ranch_tcp,keepalive,<0.643.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55168},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-19 23:48:49.416 [error] <0.582.0>@lasp_core:query_var:354 CRASH REPORT Process <0.582.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.417 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.582.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.417 [error] <0.584.0>@lasp_core:query_var:354 CRASH REPORT Process <0.584.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.418 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.584.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.418 [error] <0.425.0>@lasp_distribution_backend:handle_call:506 gen_server lasp_distribution_backend terminated with reason: no match of right hand value {error,{function_clause,[{lasp_core,query_var,[<<"test2">>,<0.427.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,354}]},{lasp_process,process,2,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_process.erl"},{line,201}]},{gen_flow,loop,3,[{file,"/home/pope/Projects/Websheets/deps/gen_flow/src/gen_flow.erl"},{line,174}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}} in lasp_distribution_backend:handle_call/3 line 506
2018-12-19 23:48:49.418 [error] <0.586.0>@lasp_core:query_var:354 CRASH REPORT Process <0.586.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.418 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.586.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.419 [error] <0.588.0>@lasp_core:query_var:354 CRASH REPORT Process <0.588.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.419 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.588.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.419 [error] <0.590.0>@lasp_core:query_var:354 CRASH REPORT Process <0.590.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.419 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.590.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.420 [error] <0.592.0>@lasp_core:query_var:354 CRASH REPORT Process <0.592.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.420 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.592.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.420 [error] <0.594.0>@lasp_core:query_var:354 CRASH REPORT Process <0.594.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.420 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.594.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.420 [error] <0.596.0>@lasp_core:query_var:354 CRASH REPORT Process <0.596.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.421 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.596.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.421 [error] <0.598.0>@lasp_core:query_var:354 CRASH REPORT Process <0.598.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.421 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.598.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.421 [error] <0.600.0>@lasp_core:query_var:354 CRASH REPORT Process <0.600.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.422 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.600.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.422 [error] <0.602.0>@lasp_core:query_var:354 CRASH REPORT Process <0.602.0> with 0 neighbours crashed with reason: no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354
2018-12-19 23:48:49.422 [error] <0.430.0>@lasp_core:query_var:354 Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.602.0> exit with reason no function clause matching lasp_core:query_var(<<"test2">>, <0.427.0>) line 354 in context child_terminated
2018-12-19 23:48:49.422 [error] <0.430.0> Supervisor lasp_process_sup had child gen_flow started with gen_flow:start_link(lasp_process, 1, [[{<<"test2">>,#Fun<lasp_process.2.33366935>}],#Fun<lasp_process.3.33366935>,{<0.425.0>,#Fun<lasp_pr..>}]) at <0.602.0> exit with reason reached_max_restart_intensity in context shutdown
2018-12-19 23:48:49.422 [error] <0.378.0> Supervisor lasp_sup had child lasp_process_sup started with lasp_process_sup:start_link() at <0.430.0> exit with reason shutdown in context child_terminated
2018-12-19 23:48:49.431 [error] <0.425.0>@lasp_distribution_backend:handle_call:506 CRASH REPORT Process lasp_distribution_backend with 3 neighbours crashed with reason: no match of right hand value {error,{function_clause,[{lasp_core,query_var,[<<"test2">>,<0.427.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,354}]},{lasp_process,process,2,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_process.erl"},{line,201}]},{gen_flow,loop,3,[{file,"/home/pope/Projects/Websheets/deps/gen_flow/src/gen_flow.erl"},{line,174}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}} in lasp_distribution_backend:handle_call/3 line 506
2018-12-19 23:48:49.619 [error] <0.378.0>@lasp_distribution_backend:handle_call:506 Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.425.0> exit with reason no match of right hand value {error,{function_clause,[{lasp_core,query_var,[<<"test2">>,<0.427.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,354}]},{lasp_process,process,2,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_process.erl"},{line,201}]},{gen_flow,loop,3,[{file,"/home/pope/Projects/Websheets/deps/gen_flow/src/gen_flow.erl"},{line,174}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}} in lasp_distribution_backend:handle_call/3 line 506 in context child_terminated
2018-12-19 23:50:46.832 [error] <0.560.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.55>,ranch_tcp,keepalive,<0.560.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55304},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-19 23:51:03.837 [error] <0.568.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 2,function => render,message => nil,module => 'Elixir.WebsheetsWeb.LaspView',reason => nil},[{'Elixir.WebsheetsWeb.LaspView',render,[<<"create.json">>,#{conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Adapters.Cowboy.Conn',{http_req,#Port<0.58>,ranch_tcp,keepalive,<0.568.0>,<<"GET">>,'HTTP/1.1',{{127,0,0,1},55310},<<"localhost">>,undefined,4000,<<"/api/create">>,undefined,<<>>,undefined,...}},...},...}],...},...]},...}
2018-12-21 15:53:00.076 [error] <0.560.0> Ranch listener 'Elixir.WebsheetsWeb.Endpoint.HTTP' terminated with reason: {{#{'__exception__' => true,'__struct__' => 'Elixir.Poison.EncodeError',message => nil,value => {new_table_id,<<"1EgZoqXjE2T6LQM3ztFwXZkEb6Q">>}},[{'Elixir.Poison.Encoder.Any',encode,2,[{file,"lib/poison/encoder.ex"},{line,383}]},{'Elixir.Poison.Encoder.List','-encode/3-fun-0-',3,[{file,"lib/poison/encoder.ex"},{line,259}]},{'Elixir.Poison.Encoder.List',encode,3,[{file,"lib/poison/encoder.ex"},{line,260}]},{'Elixir.Poison','encode!',2,[{file,"lib/poison.ex"},{line,41}]},{'Elixir.Phoenix.Controller',...},...]},...}
2018-12-22 14:40:44.965 [error] <0.787.0> gen_server <0.787.0> terminated with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 14:40:45.018 [error] <0.787.0> CRASH REPORT Process <0.787.0> with 0 neighbours exited with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 14:42:48.966 [error] <0.568.0> gen_server <0.568.0> terminated with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 14:42:48.978 [error] <0.568.0> CRASH REPORT Process <0.568.0> with 0 neighbours exited with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 14:45:07.597 [error] <0.589.0> gen_server <0.589.0> terminated with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 14:45:07.618 [error] <0.589.0> CRASH REPORT Process <0.589.0> with 0 neighbours exited with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 17:00:06.018 [error] <0.577.0> gen_server <0.577.0> terminated with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 17:00:06.032 [error] <0.577.0> CRASH REPORT Process <0.577.0> with 0 neighbours exited with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 17:04:15.238 [error] <0.595.0> gen_server <0.595.0> terminated with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 17:04:15.259 [error] <0.595.0> CRASH REPORT Process <0.595.0> with 0 neighbours exited with reason: {aborted,{no_exists,[lasp_table,nil]}} in mnesia:abort/1 line 355
2018-12-22 17:14:47.832 [error] <0.442.0>@mensia:start CRASH REPORT Process <0.442.0> with 0 neighbours exited with reason: call to undefined function mensia:start() in application_master:init/4 line 138
2018-12-22 17:15:36.138 [error] <0.620.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:23 gen_server <0.620.0> terminated with reason: call to undefined function erlang:update_integer/1 from 'Elixir.WebsheetsWeb.UpdateChannel':handle_in/3 line 23
2018-12-22 17:15:36.154 [error] <0.620.0>@erlang:update_integer CRASH REPORT Process <0.620.0> with 0 neighbours crashed with reason: call to undefined function erlang:update_integer([monotonic,positive])
2018-12-22 17:16:38.748 [error] <0.426.0>@lasp_core:update:435 gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update([], {apply,nil,{set,2,nil}}, <0.611.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435
2018-12-22 17:16:38.781 [error] <0.426.0>@lasp_core:update:435 CRASH REPORT Process lasp_distribution_backend with 3 neighbours crashed with reason: no function clause matching lasp_core:update([], {apply,nil,{set,2,nil}}, <0.611.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435
2018-12-22 17:16:38.781 [error] <0.379.0>@lasp_core:update:435 Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.426.0> exit with reason no function clause matching lasp_core:update([], {apply,nil,{set,2,nil}}, <0.611.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435 in context child_terminated
2018-12-22 17:16:38.781 [error] <0.611.0> gen_server <0.611.0> terminated with reason: {{function_clause,[{lasp_core,update,[[],{apply,nil,{set,2,nil}},<0.611.0>,#Fun<lasp_distribution_backend.47.56534003>,#Fun<lasp_distribution_backend.48.56534003>,<0.428.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,435}]},{lasp_distribution_backend,handle_call,3,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_distribution_backend.erl"},{line,603}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"..."},...]},...]},...} in gen_server:call/3 line 223
2018-12-22 17:16:38.785 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours exited with reason: {{function_clause,[{lasp_core,update,[[],{apply,nil,{set,2,nil}},<0.611.0>,#Fun<lasp_distribution_backend.47.56534003>,#Fun<lasp_distribution_backend.48.56534003>,<0.428.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,435}]},{lasp_distribution_backend,handle_call,3,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_distribution_backend.erl"},{line,603}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"..."},...]},...]},...} in gen_server:call/3 line 223
2018-12-22 17:23:03.438 [error] <0.426.0>@lasp_core:update:435 gen_server lasp_distribution_backend terminated with reason: no function clause matching lasp_core:update([], {apply,nil,{set,2,#{nil => nil}}}, <0.609.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435
2018-12-22 17:23:03.456 [error] <0.426.0>@lasp_core:update:435 CRASH REPORT Process lasp_distribution_backend with 3 neighbours crashed with reason: no function clause matching lasp_core:update([], {apply,nil,{set,2,#{nil => nil}}}, <0.609.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435
2018-12-22 17:23:03.456 [error] <0.379.0>@lasp_core:update:435 Supervisor lasp_sup had child lasp_distribution_backend started with lasp_distribution_backend:start_link() at <0.426.0> exit with reason no function clause matching lasp_core:update([], {apply,nil,{set,2,#{nil => nil}}}, <0.609.0>, #Fun<lasp_distribution_backend.47.56534003>, #Fun<lasp_distribution_backend.48.56534003>, <0.428.0>) line 435 in context child_terminated
2018-12-22 17:23:03.456 [error] <0.609.0> gen_server <0.609.0> terminated with reason: {{function_clause,[{lasp_core,update,[[],{apply,nil,{set,2,#{nil => nil}}},<0.609.0>,#Fun<lasp_distribution_backend.47.56534003>,#Fun<lasp_distribution_backend.48.56534003>,<0.428.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,435}]},{lasp_distribution_backend,handle_call,3,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_distribution_backend.erl"},{line,603}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,...},...]},...} in gen_server:call/3 line 223
2018-12-22 17:23:03.461 [error] <0.609.0> CRASH REPORT Process <0.609.0> with 0 neighbours exited with reason: {{function_clause,[{lasp_core,update,[[],{apply,nil,{set,2,#{nil => nil}}},<0.609.0>,#Fun<lasp_distribution_backend.47.56534003>,#Fun<lasp_distribution_backend.48.56534003>,<0.428.0>],[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_core.erl"},{line,435}]},{lasp_distribution_backend,handle_call,3,[{file,"/home/pope/Projects/Websheets/deps/lasp/src/lasp_distribution_backend.erl"},{line,603}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,...},...]},...} in gen_server:call/3 line 223
2018-12-22 17:40:37.621 [error] <0.610.0>@Elixir.WebsheetsWeb.UpdateChannel:handle_in:25 gen_server <0.610.0> terminated with reason: call to undefined function lasp:update/2 from 'Elixir.WebsheetsWeb.UpdateChannel':handle_in/3 line 25
2018-12-22 17:40:37.637 [error] <0.610.0>@lasp:update CRASH REPORT Process <0.610.0> with 0 neighbours crashed with reason: call to undefined function lasp:update([], {apply,nil,{set,2,#{nil => nil}}})
